### ISSUE TITLE
minor errors in the code of SAC.py

### ISSUE THREAD

**Issue by TAOGZ** [BY571/Soft-Actor-Critic-and-Extensions#2]
Thanks for your work and efforts. Your code is easily understood and reproducible.

I found a minor issue in the update of Actor loss.
1. It seems that you use critic network 1 to update the loss rather than using the minimum one of these two critic networks.
2. if use fixed alpha, there is an error in the update of Actor loss because the value actions_pred is only defined in case of auto-tuning temperature.
3.  In the Agent class: 1) the parameter add_noise in the act method is not used; 2) the weight initialization can not be done since the parameter init_w is not given.

Thank you again,
Best regards.

Tao

**Comment by BY571** [comment]
Thanks TAOGZ for the review and the mentioned errors!
ill check the problems you noticed the next days.
If you find more feel free to report them :)
