### ISSUE TITLE
understanding alpha learning

### ISSUE THREAD

**Issue by shuangwu** [BY571/Soft-Actor-Critic-and-Extensions#3]
Hi, there,
  I am confused about how alpha learning is done here:
https://github.com/BY571/Soft-Actor-Critic-and-Extensions/blob/222537fb05b821dfe3650131cba4a6a71d230a6f/SAC.py#L244

I thought line 244 here should use alpha instead of self.log_alpha to compute alpha_loss, the dependency goes like: self.log_alpha --> alpha --> alpha_loss, so that ADAM will optimize self.log_alpha automatically for us.

Thanks.

Shuang

**Comment by BY571** [comment]
you are right, thanks for mentioning it! i just updated the code
